# Generated by Django 2.0.3 on 2018-04-03 15:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('heading_text', models.CharField(max_length=200)),
                ('body_text', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link_website', models.CharField(max_length=200)),
                ('link_text', models.CharField(max_length=200)),
                ('link_href', models.CharField(max_length=100)),
            ],
        ),
    ]
