# Generated by Django 2.0.4 on 2018-04-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='domain_name',
        ),
        migrations.AddField(
            model_name='site',
            name='reference',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='short_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
